@BaseUrl= http://localhost:3000/api

###
GET http://localhost:3000/?id=5

###

GET http://localhost:3000/3

###
POST http://localhost:3000/
Content-Type: application/json

{
    "name":"oguz",
    "age":22
}

###
GET {{BaseUrl}}/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmMxNTcyNzYwZjNhMzExOGM1N2Y5ODMiLCJlbWFpbCI6Im9ndXo2MUBnbWFpbC5jb20iLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjU2ODM4NTI2LCJleHAiOjE2NTY4NDIxMjZ9.xSxXb3oWsoFf73II3-xMn6dPQKhVXmd4K1eKxH2ze3I

###
GET {{BaseUrl}}/users/home
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmMxNTcyNzYwZjNhMzExOGM1N2Y5ODMiLCJlbWFpbCI6Im9ndXo2MUBnbWFpbC5jb20iLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjU2ODM4MTEzLCJleHAiOjE2NTY4NDE3MTN9.DVTWa3E5ZC2FihEDtYW3pNckILufSw0dV_onTLBSFZk


###
GET {{BaseUrl}}/users/62bf228c9ee86961807a7702

###
POST {{BaseUrl}}/users
Content-Type: application/json

{
    "name":"xxxx",
    "username":"admxxxxin",
    "email": "x@gmail.com",
    "password":"admin"
}
###
POST {{BaseUrl}}/users/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password":"admin"
}
###

PATCH  {{BaseUrl}}/users/62c06619d35fbe10001ebe7a
Content-Type: application/json

{
    "name":"ozzzy61",
    "password":"axyzt"
}

###

DELETE {{BaseUrl}}/users/62c15ccafa0d29a9079fdb03
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiX2lkIjoiNjJjMTU4NjY2MGYzYTMxMThjNTdmOThhIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NTY4MzkzOTgsImV4cCI6MTY1Njg0Mjk5OH0.cB_3Ie5xuzoSVG1dBZPpRZtpAYfbY1iYupv5LkPnsU0

###
DELETE {{BaseUrl}}/users/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmMxNTcyNzYwZjNhMzExOGM1N2Y5ODMiLCJlbWFpbCI6Im9ndXo2MUBnbWFpbC5jb20iLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjU2ODM4NTI2LCJleHAiOjE2NTY4NDIxMjZ9.xSxXb3oWsoFf73II3-xMn6dPQKhVXmd4K1eKxH2ze3I